version: '3.7'

services:

  nginx:
    container_name: nginx
    build: ./devops/nginx/
    ports:
      - target: 80
        published: 80
    volumes:
      - ./tmp/cache:/tmp/cache
    depends_on:
      - api1
      - api2

  api1:
    container_name: api1
    build:
      context: api1
      dockerfile: Dockerfile
    volumes:
      - ./api1:/opt/api1
    env_file:
      - devops/common.env
    ports:
      - target: 5001
        published: 5001
    expose:
      - 5001
    depends_on:
      - redis

  api2:
    container_name: api2
    build:
      context: api2
      dockerfile: Dockerfile
    volumes:
      - ./api2:/opt/api2
    env_file:
      - devops/common.env
    ports:
      - target: 5002
        published: 5002
    expose:
      - 5002
    depends_on:
      - redis

    
  redis:
    container_name: redis
    image: redis:6.0.8-alpine
    ports:
      - target: 6379
        published: 6379
    expose:
      - 6379
